name: CI/CD Flask App

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: sa-east-1
  ECR_REPO: 524558748007.dkr.ecr.sa-east-1.amazonaws.com/flask-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t flask-app:${{ github.sha }} .

      - name: Tag image
        run: |
          docker tag flask-app:${{ github.sha }} \
          $ECR_REPO:${{ github.sha }}

      - name: Push image
        run: |
          docker push $ECR_REPO:${{ github.sha }}

      - name: Update latest tag
        run: |
          docker tag flask-app:${{ github.sha }} $ECR_REPO:latest
          docker push $ECR_REPO:latest